services:
  scraper:
    build:
      context: ./cache/scraper
      dockerfile: Dockerfile
    volumes:
      - ./cache/scraper:/scraper
      - ./db:/db

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./cache/redis:/redis
