services:
  cache:
    build:
      context: ./cache
      dockerfile: Dockerfile
    container_name: waze-cache
    volumes:
      - ./cache:/app/cache
      - ./db:/app/db
      - ./cache/data:/app/data
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - waze-network
    command: ["node", "index.js"]

  redis:
    container_name: waze-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./cache/data:/cache/data
    networks:
      - waze-network
    command: ["redis-server", "--appendonly", "yes"]

  pig:
    build:
      context: .
      dockerfile: ./pig/Dockerfile
    container_name: waze-pig
    volumes:
      - ./pig:/app/pig
      - ./db:/app/db
      - ./cache/data:/app/cache/data
    environment:
      - JAVA_HOME=/usr/local/openjdk-8
      - PIG_HOME=/opt/pig
      - HADOOP_HOME=/opt/hadoop
      - PATH=/opt/pig/bin:/opt/hadoop/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    networks:
      - waze-network
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: waze-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - waze-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.3
    container_name: waze-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - waze-network

  visualization:
    build:
      context: ./visualization
      dockerfile: Dockerfile
    container_name: waze-visualization
    depends_on:
      - elasticsearch
      - cache
    volumes:
      - ./db:/db               
    environment:
      - NODE_ENV=production
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - ES_INDEX=waze-events
    networks:
      - waze-network
    command: ["node", "index.js"]

volumes:
  redis-data:
  es-data:

networks:
  waze-network:
    driver: bridge
