services:
  scraper:
    build:
      context: ./cache/node
      dockerfile: Dockerfile
    volumes:
      - ./cache/node:/node
      - ./db:/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./cache/redis:/redis
