services:
  scraper:
    build:
      context: ./cache
      dockerfile: Dockerfile
    volumes:
      - ./cache:/cache
      - ./db:/db
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./cache/data:/cache/data